### ISSUE TITLE
z-index

### ISSUE THREAD

**Issue by tripplehelix** [Q42/QreditRoll#3]
I have elements on my website that always display above qreditroll. Using z-index 500 - 502

**Comment by kevnoutsawo** [comment]
Hello @tripplehelix ,
The QreditRoll script should be at the end of the body element of your website.
You can try double-checking if it's the LAST element in the body tag.
Does it help?

**Comment by tripplehelix** [comment]
No, still the same issue. The only thing after it is now what cloudflare injects.

**Comment by kevnoutsawo** [comment]
Cloudflare is known to inject code for security purposes. You can disable that behavior in Cloudflare's dashboard but it's not a great idea regarding security.
What are the elements that come on top of qreditroll?
Maybe the issue is relative to those elements' styling.

**Comment by tripplehelix** [comment]
The URL for reference is [diseworth.uk](https://diseworth.uk/)

**Comment by kevnoutsawo** [comment]
Thanks for the link. After modifying the styles a bit, I think I found the root cause of your issue.
The z-index used on those elements is too high. I could make it work nicely by lowering it to 0.
That way, the elements stay on top of the page but are just behind the QreditRoll's iframe when it's triggered. If there is no particular reason for you to set the z-index as high as 500, setting it to 0 should fix the issue.
_Try and see if it works as you would like it to._

**Comment by tripplehelix** [comment]
No it has to be at least one as otherwise the a:hover overlaps on the dialogue page. Not sure why though.

**Comment by kevnoutsawo** [comment]
That's because there are no positioning settings for the #dialogue cards so they kind of ignore the fixed elements.
I think you can solve it by setting their position to relative and applying a z-index of -1 on them.
Like this
`#dialogue .linkbox {
    position: relative;
    z-index: -1;
}`

**Comment by kevnoutsawo** [comment]
@chriswaalberg , I think this issue can be marked as solved.

**Comment by tripplehelix** [comment]
It has caused other issues. I've just removed it.

**Comment by chriswaalberg** [comment]
@tripplehelix I added a z-index, so this issue should be resolved now. What other issues did you see?

**Comment by tripplehelix** [comment]
Thank you, that has fixed it.
